# Generated by Django 4.0.6 on 2023-09-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeId', models.CharField(max_length=50)),
                ('Typename', models.CharField(max_length=100)),
                ('typeshort_name', models.CharField(max_length=50)),
                ('TypeDescription', models.CharField(max_length=200)),
                ('type_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
