# Generated by Django 4.2.5 on 2023-10-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('dateofbirth', models.DateTimeField()),
                ('maritalstatus', models.CharField(choices=[('single', 'never married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='new', max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('NoOfSiblings', models.CharField(max_length=200)),
                ('highest_qualification', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=50)),
                ('Institutions_name', models.CharField(verbose_name=100)),
                ('yearofpassout', models.DateField()),
                ('profession', models.CharField(verbose_name=100)),
                ('Current_Employment_Status', models.BooleanField(default=False)),
                ('Annual_Income', models.IntegerField()),
                ('Height', models.FloatField()),
                ('Complexion', models.CharField(max_length=100)),
                ('Body_Type', models.CharField(max_length=100)),
                ('Hobbies', models.CharField(max_length=100)),
                ('Interests', models.CharField(max_length=100)),
                ('Lifestyle', models.CharField(max_length=100)),
                ('Habits', models.TextField(max_length=100)),
                ('Diet', models.CharField(max_length=100)),
                ('Smoking_Habits', models.BooleanField(default=False)),
                ('Drinking_Habits', models.BooleanField(default=False)),
                ('Horoscope', models.TextField()),
                ('Birth_Star', models.CharField(max_length=100)),
                ('Raasi', models.CharField(max_length=100)),
                ('Time_of_Birth', models.DateTimeField()),
                ('Place_of_Birth', models.CharField(max_length=50)),
                ('About', models.TextField()),
                ('Desired_partnerage', models.IntegerField()),
                ('Preferred_educational_qualifications', models.CharField(max_length=100)),
                ('partner_profession', models.CharField(max_length=50)),
                ('partner_preference', models.TextField()),
                ('Photographs', models.ImageField(upload_to='')),
                ('quality_photograph', models.ImageField(upload_to='')),
                ('address_line_1', models.CharField(blank=True, max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
    ]
